SET DATABASE SQL SYNTAX ORA TRUE;

CREATE TABLE "TB_USUARIOS" (
    "ID" NUMERIC(15) PRIMARY KEY,
    "NOME" VARCHAR(50) NOT NULL,
    "SENHA" VARCHAR(150) NOT NULL,
    "CPF" VARCHAR(20) NOT NULL,
    "NIVEL" NUMERIC(5) NOT NULL,
    "PONTOS_ACUMULADOS" NUMERIC(15),
    "EXPERIENCIA" NUMERIC(15)
);

CREATE TABLE "USERS" (
    "USERNAME" VARCHAR(150) PRIMARY KEY,
    "PASSWORD" VARCHAR(150),
    "ENABLED" VARCHAR(5)
);

CREATE TABLE "AUTHORITIES" (
    "USERNAME" VARCHAR(150) PRIMARY KEY,
    "AUTHORITY" VARCHAR(10)
);

CREATE TABLE "TB_RECICLAGEM" (
    "ID" NUMERIC(15) PRIMARY KEY,
    "ID_FUNCIONARIO" NUMERIC(15) NOT NULL,
    "ID_PONTO_DE_RECICLAGEM" NUMERIC(15) NOT NULL,
    "MATERIAL" VARCHAR(50),
    "QUANTIDADE" NUMERIC(15,2),
    "PONTOS_GERADOS" NUMERIC(15),
    "DATA" DATE
);

CREATE TABLE "TB_PONTOS_DE_RECICLAGEM" (
    "ID" NUMERIC(15) PRIMARY KEY,
    "NOME" VARCHAR(150),
    "CNPJ" VARCHAR(20)
);

CREATE TABLE "TB_PRODUTOS" (
    "ID" NUMERIC(15) PRIMARY KEY,
    "NOME" VARCHAR(150),
    "VALOR_PONTOS" NUMERIC(15),
    "URL_IMAGEM" VARCHAR(300)
);

CREATE TABLE "TB_HISTORICO_DE_COMPRAS" (
    "ID" NUMERIC(15) PRIMARY KEY,
    "PRODUTO" VARCHAR(150),
    "PONTOS" NUMERIC(15),
    "USUARIO" NUMERIC(15)
);

CREATE SEQUENCE SQ_ID_FUNCIONARIO START WITH 10 INCREMENT BY 10;
CREATE SEQUENCE SQ_ID_RECICLAGEM START WITH 10 INCREMENT BY 1;
CREATE SEQUENCE SQ_HISTORICO_DE_COMPRAS START WITH 10 INCREMENT BY 1;

INSERT INTO "TB_USUARIOS" ("ID", "NOME", "SENHA", "CPF", "NIVEL", "PONTOS_ACUMULADOS", "EXPERIENCIA") VALUES (1, 'ADMIN', 'ADMIN',
'12345678910', 1, 10, 100);

INSERT INTO "USERS" ("USERNAME", "PASSWORD", "ENABLED") VALUES ('ADMIN', '$2a$10$mf5rGjRwr3g5PDYsAq/qqenxwFxWHi19x3NxvtTM2eP3ie7jntWkC', 'TRUE');
INSERT INTO "AUTHORITIES" ("USERNAME", "AUTHORITY") VALUES ('ADMIN', 'ADMIN');

INSERT INTO "TB_PONTOS_DE_RECICLAGEM" ("ID", "NOME", "CNPJ") VALUES (1, 'COLETA DO SEU ZÉ', '111111111');
INSERT INTO "TB_PONTOS_DE_RECICLAGEM" ("ID", "NOME", "CNPJ") VALUES (2, 'ECO PONTO', '111111111');
INSERT INTO "TB_PONTOS_DE_RECICLAGEM" ("ID", "NOME", "CNPJ") VALUES (3, 'POSTO DE COLETA', '111111111');

INSERT INTO "TB_RECICLAGEM" ("ID", "ID_FUNCIONARIO", "ID_PONTO_DE_RECICLAGEM", "MATERIAL", "QUANTIDADE", "PONTOS_GERADOS", "DATA") VALUES
(1, 1, 1, 'PLASTICO', 100.00, 10000, '2022-04-19');

INSERT INTO "TB_PRODUTOS" ("ID", "NOME", "VALOR_PONTOS", "URL_IMAGEM") VALUES (1, 'Mochila', 1000,
'mochila.jpg');
INSERT INTO "TB_PRODUTOS" ("ID", "NOME", "VALOR_PONTOS", "URL_IMAGEM") VALUES (2, 'Celular', 1000000,
'celular.png');
INSERT INTO "TB_PRODUTOS" ("ID", "NOME", "VALOR_PONTOS", "URL_IMAGEM") VALUES (3, 'Camiseta', 100,
'camiseta.png');
INSERT INTO "TB_PRODUTOS" ("ID", "NOME", "VALOR_PONTOS", "URL_IMAGEM") VALUES (4, 'Frigobar', 25000,
'frigobar.png');
INSERT INTO "TB_PRODUTOS" ("ID", "NOME", "VALOR_PONTOS", "URL_IMAGEM") VALUES (5, 'Fone de ouvido', 10000,
'fone.png');
INSERT INTO "TB_PRODUTOS" ("ID", "NOME", "VALOR_PONTOS", "URL_IMAGEM") VALUES (6, 'Cadeira gamer', 10000,
'cadeira.png');